management.info.git.mode=full

management.endpoints.web.exposure.include=health,info,env
management.endpoint.gateway.enabled=true
management.endpoint.shutdown.enabled=true
management.endpoint.health.show-details=never

spring.datasource.url=jdbc:postgresql://${DB_HOST:db-host}:${DB_PORT:5432}/${DB_NAME:appdb}

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.name=db-connection

spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.data-source-properties.assumeMinServerVersion=11.0
spring.datasource.hikari.data-source-properties.reWriteBatchedInserts=true
spring.datasource.hikari.data-source-properties.session.program=${spring.application.name}
spring.datasource.hikari.data-source-properties.ApplicationName=${spring.application.name}
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maxLifetime=600000
spring.datasource.hikari.idleTimeout=45000

# https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
spring.jpa.open-in-view=false

spring.jackson.serialization.write-dates-as-timestamps=false

logging.service-name=${spring.application.name}
logging.base-path=/var/log/advantum/service/${spring.application.name}
logging.file.name=${logging.base-path}/debug.log
management.endpoint.logfile.external-file=${logging.file.name}

